import os
from textwrap import dedent

# Bluesky username
HANDLE = "amitness.com"

# Bluesky app password, available via: https://bsky.app/settings/app-passwords
PASSWORD = os.environ["BLUESKY_APP_PASSWORD"]

# Domain provided by Cloudflare pages
SERVICE_DOMAIN = "bluesky-1tj.pages.dev"

## Feed Details

# A short name for the record that will show in urls
# Lowercase with no spaces.
# Ex: whats-hot
RECORD_NAME: str = "arxiv-feed"

# A display name for your feed
# Ex: What's Hot
DISPLAY_NAME: str = "Papers"

# (Optional) A description of your feed
# Ex: Top trending content from the whole network
DESCRIPTION: str = dedent(
    """
    Latest ML research papers and preprints from arxiv.org discussed on Bluesky.
    
    Logic:
    - Fetch arxiv preprints & filters out non-ML via arxiv API
    - Ranks the items using hackernews algorithm
    """
).strip()

SERVICE_DID = f"did:web:{SERVICE_DOMAIN}"

# Feed URI generated by running `python setup_feed.py`
FEED_URI = "at://did:plc:bpuq5cgmyvssgi3iwsyvd4gn/app.bsky.feed.generator/arxiv-feed"

# Skyfeed path
SKYFEED_PATH = (
    "at://did:plc:bpuq5cgmyvssgi3iwsyvd4gn/app.bsky.feed.generator/aaagg56kp5qzi"
)
